web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker youtrack.asgi:application --bind 0.0.0.0:$PORT --max-requests 10000 --max-requests-jitter 1000 --access-logfile -
worker: celery -A youtrack worker -l info
beat: celery -A youtrack beat -l INFO